### ISSUE TITLE
dynamic build with releases property name 

### ISSUE THREAD

**Issue by streiten** [teamtito/tito-examples#1]
what value does _releases_ids_ expect ? tried a comma seperated string and array but didn't get it to work. using _releases_ as property name instead seems to work. 

https://github.com/teamtito/tito-examples/blob/4e36987bd039502b4d04492bced5f79af4ac346c/load-tito-widget-dynamically.html#L14

**Comment by cillian** [comment]
@streiten Yes that should have been `:releases`, I have fixed that example now. Thanks.
